apiVersion: v1
kind: Pod
metadata:
  name: flask
  labels:
    name: myapp
spec:
  containers:
  - name: flaskapp-redis
    image: redis:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379
  - name: flaskapp-web
    image: nisgames/demoflaskapp-web:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
